print("Please enter your full name : ")
fullname=input()
print("Please enter nickname : ")
nickname=input()
print("Please enter your NPM : ")
npm=int(input())
print("please enter your class : ")
pylance=(input())
print("Please enter place of birth : ")
pob=input()
print("Please enter date of birth : ")
date=int(input())
print("Please enter your month of birth : ")
month=input()
print("Please enter year of birth : ")
year=int(input())
print("Please enter your phone number : ")
phone=int(input())
print("Please enter your address : ")
address=input()

dob=2021-year

print("**********")
print(f"= NAMA    : {fullname}")
print(f"= NIM     : {npm}         ")
print(f"= KELAS   : {pylance}         ")
print("**********")


print("\n\n Assalamu'alaikum. ")
print(f"Let me introduce myself, my name is {fullname}, ")
print(f"but you can call me {nickname}, my NPM {npm}, ")
print(f"I was born in {pob} and i am {dob} years old, ")
print(f"I am very glad if you want to invite my house in {address}, ")
print(f"So don't forget to call me before with the number {phone}, ")
print("\n\n Thank you ")
